export type DiseaseInfo = {
  keywords: string[];
  cause: string;
  treatment: string;
  prevention: string;
};

export const diseaseData: DiseaseInfo[] = [
  { keywords: ["powdery mildew"], cause: "Fungus (Erysiphales)", treatment: "Apply sulfur or potassium bicarbonate fungicide. Remove infected leaves.", prevention: "Improve air circulation, avoid overhead watering, plant resistant varieties." },
  { keywords: ["leaf spot"], cause: "Fungus or Bacteria", treatment: "Remove infected leaves. Apply copper-based fungicide for severe cases.", prevention: "Avoid wet foliage, water at base, ensure good air circulation." },
  { keywords: ["root rot"], cause: "Fungus (Phytophthora, Pythium, Rhizoctonia)", treatment: "Reduce watering immediately. Repot with fresh, well-draining soil. Remove rotten roots.", prevention: "Use well-draining soil, ensure pots have drainage holes, avoid overwatering." },
  { keywords: ["aphids"], cause: "Pest (Aphidoidea)", treatment: "Spray with neem oil or insecticidal soap. Introduce ladybugs.", prevention: "Check plants regularly, use reflective mulches, attract beneficial insects." },
  { keywords: ["nitrogen deficiency"], cause: "Nutrient deficiency", treatment: "Apply nitrogen-rich fertilizer (blood meal, fish emulsion).", prevention: "Use balanced fertilizer regularly, maintain soil health with compost." },
  { keywords: ["rust"], cause: "Fungus (Pucciniales)", treatment: "Remove infected leaves. Apply fungicide containing sulfur or neem oil.", prevention: "Avoid overhead watering, ensure good air circulation, clean up fallen leaves." },
  { keywords: ["mosaic virus"], cause: "Virus", treatment: "Remove infected plants. No cure available.", prevention: "Control aphids (vectors), sterilize tools, use virus-free seeds." },
  { keywords: ["blight"], cause: "Fungus or Bacteria", treatment: "Prune infected areas. Apply copper fungicide.", prevention: "Space plants properly, avoid overhead watering, rotate crops." },
  { keywords: ["scale insects"], cause: "Pest (Coccoidea)", treatment: "Apply horticultural oil or neem oil. Scrape off manually.", prevention: "Regular inspection, prune infested branches, maintain plant health." },
  { keywords: ["spider mites"], cause: "Pest (Tetranychidae)", treatment: "Spray with water. Apply miticide or neem oil.", prevention: "Increase humidity, regular misting, quarantine new plants." },
  { keywords: ["downy mildew"], cause: "Fungus (Peronosporaceae)", treatment: "Apply copper-based fungicide. Remove affected leaves.", prevention: "Improve air circulation, avoid wet leaves, use resistant varieties." },
  { keywords: ["anthracnose"], cause: "Fungus (Colletotrichum)", treatment: "Apply fungicide containing chlorothalonil. Prune infected areas.", prevention: "Avoid overhead watering, remove plant debris, ensure good drainage." },
  { keywords: ["fusarium wilt"], cause: "Fungus (Fusarium oxysporum)", treatment: "Remove infected plants. Solarize soil.", prevention: "Use resistant varieties, practice crop rotation, sterilize tools." },
  { keywords: ["verticillium wilt"], cause: "Fungus (Verticillium)", treatment: "Prune affected branches. No chemical cure.", prevention: "Plant resistant varieties, avoid overwatering, improve soil drainage." },
  { keywords: ["canker"], cause: "Fungus or Bacteria", treatment: "Prune infected branches 4-6 inches below canker. Apply copper fungicide.", prevention: "Avoid wounding plants, prune in dry weather, sterilize pruning tools." },
  { keywords: ["black spot"], cause: "Fungus (Diplocarpon rosae)", treatment: "Apply fungicide containing myclobutanil or chlorothalonil.", prevention: "Water at base, remove fallen leaves, ensure good air circulation." },
  { keywords: ["white mold"], cause: "Fungus (Sclerotinia sclerotiorum)", treatment: "Remove infected plant parts. Apply fungicide.", prevention: "Improve air circulation, avoid overcrowding, practice crop rotation." },
  { keywords: ["gray mold"], cause: "Fungus (Botrytis cinerea)", treatment: "Remove infected flowers and leaves. Apply fungicide.", prevention: "Improve air circulation, avoid overhead watering, remove dead plant material." },
  { keywords: ["damping off"], cause: "Fungus (Pythium, Rhizoctonia)", treatment: "Remove affected seedlings. Apply fungicide.", prevention: "Use sterile potting mix, avoid overwatering, provide good air circulation." },
  { keywords: ["clubroot"], cause: "Fungus (Plasmodiophora brassicae)", treatment: "Remove infected plants. Raise soil pH to 7.2+.", prevention: "Practice 7-year crop rotation, improve drainage, use resistant varieties." },
  { keywords: ["scab"], cause: "Fungus (Venturia)", treatment: "Apply fungicide containing captan or sulfur.", prevention: "Rake fallen leaves, prune for air circulation, use resistant varieties." },
  { keywords: ["fire blight"], cause: "Bacteria (Erwinia amylovora)", treatment: "Prune infected branches 12 inches below infection. Apply streptomycin.", prevention: "Avoid heavy pruning, sterilize tools, use resistant varieties." },
  { keywords: ["bacterial leaf spot"], cause: "Bacteria (Xanthomonas)", treatment: "Apply copper-based bactericide. Remove infected leaves.", prevention: "Avoid overhead watering, rotate crops, use disease-free seeds." },
  { keywords: ["bacterial wilt"], cause: "Bacteria (Ralstonia solanacearum)", treatment: "Remove infected plants. Solarize soil.", prevention: "Practice crop rotation, use resistant varieties, control insects." },
  { keywords: ["crown gall"], cause: "Bacteria (Agrobacterium tumefaciens)", treatment: "Remove galls surgically. No chemical cure.", prevention: "Avoid wounding roots, use certified disease-free plants." },
  { keywords: ["tomato hornworm"], cause: "Pest (Manduca quinquemaculata)", treatment: "Handpick caterpillars. Apply Bt (Bacillus thuringiensis).", prevention: "Encourage parasitic wasps, till soil in fall, use row covers." },
  { keywords: ["whitefly"], cause: "Pest (Trialeurodes vaporariorum)", treatment: "Apply neem oil or insecticidal soap. Use yellow sticky traps.", prevention: "Check plants regularly, use reflective mulch, introduce beneficial insects." },
  { keywords: ["thrips"], cause: "Pest (Thysanoptera)", treatment: "Apply spinosad or neem oil. Use blue sticky traps.", prevention: "Remove weeds, use reflective mulch, introduce predatory mites." },
  { keywords: ["mealybugs"], cause: "Pest (Pseudococcidae)", treatment: "Apply rubbing alcohol with cotton swab. Use neem oil.", prevention: "Inspect new plants, avoid over-fertilizing, introduce ladybugs." },
  { keywords: ["caterpillars"], cause: "Pest (Lepidoptera larvae)", treatment: "Handpick. Apply Bt (Bacillus thuringiensis).", prevention: "Use row covers, encourage birds, inspect plants regularly." },
  { keywords: ["slugs"], cause: "Pest (Gastropoda)", treatment: "Set beer traps. Apply iron phosphate bait.", prevention: "Remove debris, water in morning, use copper tape around plants." },
  { keywords: ["snails"], cause: "Pest (Gastropoda)", treatment: "Handpick at night. Apply iron phosphate bait.", prevention: "Remove hiding places, use copper barriers, encourage natural predators." },
  { keywords: ["cutworms"], cause: "Pest (Noctuidae larvae)", treatment: "Apply Bt or spinosad. Use cardboard collars around stems.", prevention: "Till soil before planting, remove plant debris, use diatomaceous earth." },
  { keywords: ["grasshoppers"], cause: "Pest (Caelifera)", treatment: "Apply neem oil or insecticidal soap. Use baits containing carbaryl.", prevention: "Keep grass short, use row covers, encourage birds and praying mantis." },
  { keywords: ["japanese beetles"], cause: "Pest (Popillia japonica)", treatment: "Handpick. Apply neem oil or pyrethrin.", prevention: "Use pheromone traps away from garden, introduce beneficial nematodes." },
  { keywords: ["potassium deficiency"], cause: "Nutrient deficiency", treatment: "Apply potassium-rich fertilizer (potash, greensand).", prevention: "Use balanced fertilizer, add compost, maintain proper pH." },
  { keywords: ["phosphorus deficiency"], cause: "Nutrient deficiency", treatment: "Apply bone meal or rock phosphate.", prevention: "Test soil regularly, use balanced fertilizer, add organic matter." },
  { keywords: ["iron deficiency"], cause: "Nutrient deficiency (Iron chlorosis)", treatment: "Apply iron chelates or iron sulfate.", prevention: "Maintain proper soil pH, improve drainage, add organic matter." },
  { keywords: ["magnesium deficiency"], cause: "Nutrient deficiency", treatment: "Apply Epsom salts (magnesium sulfate).", prevention: "Use dolomitic lime, avoid excessive potassium, add compost." },
  { keywords: ["calcium deficiency"], cause: "Nutrient deficiency (Blossom end rot)", treatment: "Apply calcium nitrate or gypsum. Water consistently.", prevention: "Maintain even soil moisture, avoid over-fertilizing with nitrogen." },
  { keywords: ["zinc deficiency"], cause: "Nutrient deficiency", treatment: "Apply zinc sulfate or chelated zinc.", prevention: "Maintain proper pH, avoid over-fertilizing with phosphorus." },
  { keywords: ["manganese deficiency"], cause: "Nutrient deficiency", treatment: "Apply manganese sulfate.", prevention: "Maintain proper soil pH, improve drainage, add organic matter." },
  { keywords: ["boron deficiency"], cause: "Nutrient deficiency", treatment: "Apply borax or boric acid (carefully - toxic in excess).", prevention: "Test soil, use compost, avoid over-liming." },
  { keywords: ["copper deficiency"], cause: "Nutrient deficiency", treatment: "Apply copper sulfate.", prevention: "Use balanced fertilizer, maintain proper pH, add organic matter." },
  { keywords: ["sunscald"], cause: "Environmental stress", treatment: "Provide shade cloth. Damaged tissue won't recover.", prevention: "Provide afternoon shade, use shade cloth, maintain leaf cover." },
  { keywords: ["frost damage"], cause: "Environmental stress (Cold injury)", treatment: "Prune damaged tissue in spring. Water before freeze.", prevention: "Cover plants during frost, plant after last frost date, use frost cloth." },
  { keywords: ["heat stress"], cause: "Environmental stress", treatment: "Water deeply. Provide shade.", prevention: "Mulch soil, water consistently, provide afternoon shade." },
  { keywords: ["wind damage"], cause: "Environmental stress", treatment: "Prune broken branches. Stake damaged plants.", prevention: "Install windbreaks, stake tall plants, choose sheltered location." },
  { keywords: ["hail damage"], cause: "Environmental stress", treatment: "Prune damaged tissue. Apply fungicide to wounds.", prevention: "Use row covers, plant in sheltered areas, monitor weather forecasts." },
  { keywords: ["flooding"], cause: "Environmental stress (Oxygen deprivation)", treatment: "Improve drainage. Remove standing water.", prevention: "Plant in raised beds, improve soil drainage, avoid low-lying areas." },
  { keywords: ["drought stress"], cause: "Environmental stress (Water deficiency)", treatment: "Water deeply and slowly. Apply mulch.", prevention: "Use drip irrigation, mulch heavily, choose drought-tolerant plants." },
  { keywords: ["herbicide damage"], cause: "Chemical injury", treatment: "Remove affected growth. Water thoroughly to dilute.", prevention: "Read labels carefully, avoid spraying on windy days, use targeted application." },
  { keywords: ["salt damage"], cause: "Chemical injury (Soil salinity)", treatment: "Leach soil with water. Apply gypsum.", prevention: "Avoid over-fertilizing, use quality water, test soil regularly." },
];